name: .NET Core 3.1 Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for git

      # Setup .NET Core 3.1 SDK
      - name: Setup .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      # Verify directories and proceed with build steps...
