name: .NET Core 3.1 Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      # Print the working directory to confirm where GitHub Actions is operating
      - name: Print working directory
        run: |
          echo "GitHub workspace: ${{ github.workspace }}"
          echo "Current directory: $(pwd)"
          ls -la

      # Create a folder and add a basic .NET console project
      - name: Create .NET Core 3.1 project
        run: |
          mkdir -p "${{ github.workspace }}/HelloWorldApp"
          dotnet new console -o "${{ github.workspace }}/HelloWorldApp"
          echo 'Console.WriteLine("Hello, World!");' > "${{ github.workspace }}/HelloWorldApp/Program.cs"
        
      # Confirm the folder structure after creating the project
      - name: List HelloWorldApp contents
        run: |
          ls -la "${{ github.workspace }}/HelloWorldApp"

      # Build the .NET Core project
      - name: Build the project
        run: dotnet build "${{ github.workspace }}/HelloWorldApp"

      # Run the .NET Core application
      - name: Run the application
        run: dotnet run --project "${{ github.workspace }}/HelloWorldApp"
